<?php


namespace app\view\controller;


use app\db\model\Student;
use think\Controller;

class Index extends Controller
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

//        $this->filter(function ($content){
//            return str_replace('-','_',$content);
//        });
    }

    public function index()
    {

//        return $this->fetch();
//        return $this->fetch('test@shi_kong/view');
//        return view('test@shi_kong/view');

//        $this->assign('student',['studentName'=>'test']);
//        return $this->fetch('db@student/view');

        $this->assign('name', 'Shikong');

//        $this->assign([
//            'user' => 'Hacker-Shikong',
//            "email" => "9194114176@qq.com"
//        ]);
//        return $this->fetch('index');

        $this->filter(function ($content){
            return str_replace('-','_',$content);
        });

        return $this->fetch('index', [
            'user' => 'Hacker-Shikong',
            "email" => "9194114176@qq.com"
        ]);

    }

    public function testDisplay(){

        $content = '{$user}.{$email}';

        return $this->display($content,[
            'user' => 'Hacker-Shikong',
            "email" => "9194114176@qq.com"
        ]);
    }

    public function varOutput(){
        $this->assign([
            'name' => 'ThinkPHP',
            'email' => "919411476@qq.com",
            'password' => "123456",
            'time' => time(),
            'float' => "123.45"
        ]);

        return $this->fetch('var');
    }

    public function loop(){
        $data = Student::all();

        $this->assign('data',$data);

        return $this->fetch('loop');
    }

    public function compare(){
        return $this->fetch('compare',[
            "author" => "Shikong"
        ]);
    }

    public function condition(){

        return $this->fetch("condition",[
            "num" => 10
        ]);
    }

    public function block(){

        // 临时控制是否开启 LayOut 布局
        $this->view->engine->layout(true);

        return $this->fetch('block',[
            'title'=>'测试标题',
            "keywords"=>"测试,php,tp,thinkPHP"
        ]);
    }

    public function extend(){
        return $this->fetch("extend",[
            "title" => "测试标题"
        ]);
    }

    public function other(){
        return $this->fetch('other',[
            'name'=>'Hacker-Shikong',
        ]);
    }

    public function test(){
        return $this->fetch('other');
    }

    public function code(){
        return $this->fetch('code');
    }
}